import { useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { DropDown } from '.'
import Web3Context from '../store/web3-context'
import { useRouter } from 'next/router'
import { addrsSubStr } from '../global/helper'
import { ConnectMetaMask } from '../services/MetaMask'
import { Alert } from '../components'

export default function Header() {
  const web3Ctx = useContext(Web3Context)
  // console.log("account-",web3Ctx.account)
  const [alert, setAlert] = useState()
  const router = useRouter()

  const connectMeta = async () => {
    await ConnectMetaMask().then((result) => {
      if (result != undefined && result != null) {
        web3Ctx.loadAccount(result)
        setAlert({
          show: true,
          title: 'Wallet Connected',
          type: 'success',
          message: 'account connected successfully',
        })
      }
    })
  }

  useEffect(() => {
    if (window.ethereum) {
      window.ethereum.on('chainChanged', () => {
        // window.location.reload()
      })
    }
    window.ethereum.on('accountsChanged', function (accounts) {
      // Time to reload your interface with accounts[0]!
      web3Ctx.loadAccount(accounts[0])
      setAlert({
        show: true,
        title: 'Account changed',
        type: 'info',
        message: 'switched to ' + accounts[0],
      })
    })

    var st_addrs = sessionStorage.getItem('address')
    if (st_addrs) web3Ctx.loadAccount(st_addrs)
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
        />
      </Head>

      {alert && (
        <Alert {...alert} onClose={() => setAlert({ ...alert, show: false })} />
      )}

      <header>
        <nav className="flex py-5 px-20 items-center justify-between bg-primary dark:bg-primary">
          <div className="flex">
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
            <p className="font-bold">NFT Marketplace</p>
          </div>
          {false && (
            <div className="flex-initial ease-in duration-500 ">
              <div className="flex justify-center border border-solid border-gray-300 rounded">
                <span
                  className="flex items-center px-3 py-1.5 text-base font-normal text-gray-700 text-center whitespace-nowrap rounded"
                  id="basic-addon2"
                >
                  <span className="material-symbols-outlined text-gray-400">
                    search
                  </span>
                </span>
                <input
                  type="search"
                  className="form-control relative flex-auto min-w-0 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding  transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                  placeholder="Search items, collections, and accounts"
                  aria-label="Search"
                  aria-describedby="button-addon2"
                />
              </div>
            </div>
          )}

          <div className="flex justify-between items-center">
            <DropDown />

            {web3Ctx?.account ? (
              <button onClick={() => router.push('/Profile')}>
                <img
                  src={`https://avatars.dicebear.com/api/miniavs/${web3Ctx.account}.svg`}
                  className="w-8 h-8 rounded-full border border-sky-400 ml-5"
                />
                <p className="text-xs font-extralight absolute text-gray-400 ">
                  {addrsSubStr(web3Ctx.account)}
                </p>
              </button>
            ) : (
              <button onClick={() => connectMeta()}>
                <span className="material-symbols-outlined mx-5">
                  account_balance_wallet
                </span>
              </button>
            )}
            {/*   <Link href="/explore"><a className="px-5 text-xs">Explore</a></Link>
            <Link href="/profile"><a className="px-5">Wallet</a></Link> */}
          </div>
        </nav>
      </header>
    </>
  )
}
